title: cfgResponse
x-stoplight:
  id: nmjdhs4gawcqj
type: object
description: Contains the response after applying device configuration changes.
properties:
  ethConfig:
    $ref: ../payload/ethConfigPayload.yaml
  wifiConfigResp:
    $ref: ../payload/cfgWifiPayload.yaml
  epConfig:
    $ref: ../payload/cfgEndpointPayload.yaml
  wifiProfiles:
    $ref: ./getWifiResponse.yaml
