import React, { type JSX } from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';
import useBaseUrl from '@docusaurus/useBaseUrl';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import { useLocation } from '@docusaurus/router';
import styles from '@site/src/css/download-pdf-button.module.scss';

/**
 * DownloadPdfButton — a native `<a download>` link to a pre-generated static
 * PDF, styled as a secondary button and placed beside the "Copy page" dropdown
 * on API-reference pages.
 *
 * Two modes:
 *   • kind="page" — the current command/event page's PDF, at /pdf<route>.pdf
 *                   (mirrors the page route; generated by scripts/generate-pdfs.mjs).
 *   • kind="full" — the consolidated API reference, at
 *                   /pdf/reference/api-reference-full.pdf (shown on api-overview).
 *
 * Rendered inside <BrowserOnly> on purpose: the target PDFs are produced AFTER
 * `docusaurus build` (in CI), so they do not exist when Docusaurus runs its
 * broken-link check over the server-rendered HTML. Keeping the <a> out of the
 * SSR output means onBrokenLinks:'throw' never sees (and never rejects) the link.
 */

const DownloadIcon = (): JSX.Element => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
    <polyline points="7 10 12 15 17 10" />
    <line x1="12" y1="15" x2="12" y2="3" />
  </svg>
);

function Inner({ kind }: { kind: 'page' | 'full' }): JSX.Element {
  const { pathname } = useLocation();
  const { siteConfig } = useDocusaurusContext();
  const { baseUrl } = siteConfig; // e.g. "/zebra-handheld-rfid-iotc/"
  // useLocation().pathname INCLUDES the site baseUrl — strip it to a route-relative slug.
  const route = pathname.startsWith(baseUrl) ? `/${pathname.slice(baseUrl.length)}` : pathname;
  const slug = route.replace(/\/$/, ''); // e.g. /reference/mgmt/get-status
  const rel = kind === 'full' ? '/pdf/reference/api-reference-full.pdf' : `/pdf${slug}.pdf`;
  const href = useBaseUrl(rel);
  const leaf = slug.split('/').pop() || 'page';
  const downloadName = kind === 'full' ? 'zebra-iotc-api-reference.pdf' : `zebra-iotc-${leaf}.pdf`;
  const label = kind === 'full' ? 'Download the full API reference (Full PDF)' : 'Download this page as PDF';
  const text = kind === 'full' ? 'Full PDF' : 'PDF';

  return (
    <a
      className={styles.downloadPdfButton}
      href={href}
      download={downloadName}
      aria-label={label}
      title={label}
    >
      <DownloadIcon />
      <span className={styles.downloadPdfText}>{text}</span>
    </a>
  );
}

export default function DownloadPdfButton({ kind = 'page' }: { kind?: 'page' | 'full' }): JSX.Element {
  return <BrowserOnly>{() => <Inner kind={kind} />}</BrowserOnly>;
}
